### ISSUE TITLE
Security Error on IE 11.0.9

### ISSUE THREAD

**Issue by innamhunzai** [sampumon/SVG.toDataURL#10]
While testing the demo on IE 11.0.9 I got security Error. 

[Console Capture](https://i.imgur.com/40HgIru.png)

**Comment by matti** [comment]
@sampumon please help us!

**Comment by innamhunzai** [comment]
Hi @matti,
 
   I was able to solve this by using [canvg](https://github.com/canvg) , there is [comment](https://github.com/sampumon/SVG.toDataURL/blob/master/butterfly_test.html#L14) in example read it and follow the instruction it will work 👍

**Comment by matti** [comment]
cool, @sampumon this can be closed!

**Comment by sampumon** [comment]
Thanks, good to know IE11 does not support native PNG export! Closing 🎉
